---
- name: Remove applications from dock
  shell: "dockutil --remove '{{ item }}'"
  ignore_errors: true
  with_items: "{{ macos_dock.applications.remove }}"

- name: Find or add applications to dock
  shell: "dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'"
  with_items: "{{ macos_dock.applications.add }}"

- name: Reorder Applications
  shell: "dockutil --move '{{ item.name }}' --position {{ item.pos }}"
  with_items: "{{ macos_dock.applications.add }}"

- name: Remove folder from dock
  shell: "dockutil --remove '{{ item }}'"
  with_items: "{{ macos_dock.folder.remove }}"

- name: Add folder to dock
  shell: "dockutil --add '{{ item.path }}' --view {{ item.view }} --display {{ item.display }}"
  with_items: "{{ macos_dock.folder.add }}"
  when:
    - item.view in [ "grid", "fan", "list", "auto" ]
    - item.display in [ "folder", "stack" ]

- name: Remove URL from dock
  shell: "dockutil --remove '{{ item }}'"
  with_items: "{{ macos_dock.url.remove }}"

- name: Add URL to dock
  shell: "dockutil --add '{{ item.url }}' --label '{{ item.label }}'"
  with_items: "{{ macos_dock.url.add }}"
  when:
    - item.url
    - item.label
